apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: pgvector/pgvector:pg17
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata

          env:
            - name: POSTGRES_PASSWORD
              value: "Qv4qKmNI3Dptv9O2" 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  annotations: 
      external-dns.alpha.kubernetes.io/hostname: postgresql.homelab.services
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres